CREATE TYPE "gender" AS ENUM('MALE', 'FEMALE');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_provider_id_account_id_unique" UNIQUE("provider_id","account_id")
);
--> statement-breakpoint
CREATE TABLE "address" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL UNIQUE,
	"line_1" text NOT NULL,
	"line_2" text,
	"city_municipality" text NOT NULL,
	"province_state_region" text NOT NULL,
	"postal_code" text NOT NULL,
	"country_code" text NOT NULL,
	"latitude" numeric,
	"longitude" numeric,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_trail" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_trail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL UNIQUE,
	"organization_id" text,
	"user_id" text,
	"component" text NOT NULL,
	"action" text NOT NULL,
	"description" text NOT NULL,
	"record_table" text,
	"record_id" text,
	"record_data_old" jsonb,
	"record_data_new" jsonb,
	"ip_address" text,
	"user_agent" text,
	"logged_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invitation" (
	"id" text PRIMARY KEY,
	"email" text NOT NULL,
	"inviter_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_organization_id_user_id_unique" UNIQUE("organization_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "object_storage" (
	"id" text PRIMARY KEY,
	"size" bigint NOT NULL,
	"mime_type" text,
	"hash_sha256" text NOT NULL UNIQUE,
	"is_public" boolean DEFAULT false NOT NULL,
	"is_uploaded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "object_storage_acl" (
	"object_storage_id" text NOT NULL,
	"user_id" text NOT NULL,
	"mode" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "object_storage_acl_object_storage_id_user_id_unique" UNIQUE("object_storage_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"slug" text NOT NULL UNIQUE,
	"logo" text,
	"metadata" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organization_slug_check" CHECK (slug = LOWER(slug))
);
--> statement-breakpoint
CREATE TABLE "permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component" text NOT NULL,
	"action" text NOT NULL,
	"role_id" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "permission_component_action_role_id_unique" UNIQUE("component","action","role_id")
);
--> statement-breakpoint
CREATE TABLE "role" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text NOT NULL UNIQUE,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "role_name_check" CHECK (name = LOWER(name))
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"token" text NOT NULL UNIQUE,
	"expires_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"active_organization_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "two_factor" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"secret" text,
	"backup_codes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upload" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"is_committed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upload_attachment" (
	"upload_id" text NOT NULL,
	"object_storage_id" text NOT NULL,
	CONSTRAINT "upload_attachment_upload_id_object_storage_id_unique" UNIQUE("upload_id","object_storage_id")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"username" text NOT NULL UNIQUE,
	"display_username" text,
	"two_factor_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_check" CHECK (email = LOWER(email)),
	CONSTRAINT "user_username_check" CHECK (username = LOWER(username))
);
--> statement-breakpoint
CREATE TABLE "user_attribute" (
	"user_id" text PRIMARY KEY,
	"is_locked" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_profile" (
	"user_id" text PRIMARY KEY,
	"first_name" text NOT NULL,
	"middle_name" text,
	"last_name" text NOT NULL,
	"name_extension" text,
	"gender" "gender" NOT NULL,
	"backup_phone_number" text,
	"address_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_relationship" (
	"user_id" text PRIMARY KEY,
	"name" text NOT NULL,
	"relationship" text NOT NULL,
	"phone_number" text NOT NULL,
	"backup_phone_number" text,
	"email" text,
	"address_id" bigint,
	"is_emergency_contact" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY,
	"identifier" text NOT NULL UNIQUE,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "account_user_id_index" ON "account" ("user_id");--> statement-breakpoint
CREATE INDEX "audit_trail_organization_id_index" ON "audit_trail" ("organization_id");--> statement-breakpoint
CREATE INDEX "audit_trail_user_id_index" ON "audit_trail" ("user_id");--> statement-breakpoint
CREATE INDEX "invitation_email_index" ON "invitation" ("email");--> statement-breakpoint
CREATE INDEX "invitation_inviter_id_index" ON "invitation" ("inviter_id");--> statement-breakpoint
CREATE INDEX "invitation_organization_id_index" ON "invitation" ("organization_id");--> statement-breakpoint
CREATE INDEX "invitation_role_index" ON "invitation" ("role");--> statement-breakpoint
CREATE INDEX "member_user_id_index" ON "member" ("user_id");--> statement-breakpoint
CREATE INDEX "member_organization_id_index" ON "member" ("organization_id");--> statement-breakpoint
CREATE INDEX "member_role_index" ON "member" ("role");--> statement-breakpoint
CREATE INDEX "object_storage_acl_object_storage_id_index" ON "object_storage_acl" ("object_storage_id");--> statement-breakpoint
CREATE INDEX "object_storage_acl_user_id_index" ON "object_storage_acl" ("user_id");--> statement-breakpoint
CREATE INDEX "permission_role_id_index" ON "permission" ("role_id");--> statement-breakpoint
CREATE INDEX "session_user_id_index" ON "session" ("user_id");--> statement-breakpoint
CREATE INDEX "session_active_organization_id_index" ON "session" ("active_organization_id");--> statement-breakpoint
CREATE INDEX "two_factor_user_id_index" ON "two_factor" ("user_id");--> statement-breakpoint
CREATE INDEX "upload_user_id_index" ON "upload" ("user_id");--> statement-breakpoint
CREATE INDEX "upload_attachment_upload_id_index" ON "upload_attachment" ("upload_id");--> statement-breakpoint
CREATE INDEX "upload_attachment_object_storage_id_index" ON "upload_attachment" ("object_storage_id");--> statement-breakpoint
CREATE INDEX "user_attribute_user_id_index" ON "user_attribute" ("user_id");--> statement-breakpoint
CREATE INDEX "user_profile_user_id_index" ON "user_profile" ("user_id");--> statement-breakpoint
CREATE INDEX "user_profile_address_id_index" ON "user_profile" ("address_id");--> statement-breakpoint
CREATE INDEX "user_relationship_user_id_index" ON "user_relationship" ("user_id");--> statement-breakpoint
CREATE INDEX "user_relationship_address_id_index" ON "user_relationship" ("address_id");--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "audit_trail" ADD CONSTRAINT "audit_trail_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "audit_trail" ADD CONSTRAINT "audit_trail_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_inviter_id_user_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_role_role_name_fkey" FOREIGN KEY ("role") REFERENCES "role"("name");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_role_role_name_fkey" FOREIGN KEY ("role") REFERENCES "role"("name");--> statement-breakpoint
ALTER TABLE "object_storage_acl" ADD CONSTRAINT "object_storage_acl_object_storage_id_object_storage_id_fkey" FOREIGN KEY ("object_storage_id") REFERENCES "object_storage"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "object_storage_acl" ADD CONSTRAINT "object_storage_acl_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "permission" ADD CONSTRAINT "permission_role_id_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id");--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_active_organization_id_organization_id_fkey" FOREIGN KEY ("active_organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "two_factor" ADD CONSTRAINT "two_factor_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "upload" ADD CONSTRAINT "upload_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "upload_attachment" ADD CONSTRAINT "upload_attachment_upload_id_upload_id_fkey" FOREIGN KEY ("upload_id") REFERENCES "upload"("id");--> statement-breakpoint
ALTER TABLE "upload_attachment" ADD CONSTRAINT "upload_attachment_object_storage_id_object_storage_id_fkey" FOREIGN KEY ("object_storage_id") REFERENCES "object_storage"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "user_attribute" ADD CONSTRAINT "user_attribute_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "user_profile" ADD CONSTRAINT "user_profile_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "user_profile" ADD CONSTRAINT "user_profile_address_id_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "address"("id");--> statement-breakpoint
ALTER TABLE "user_relationship" ADD CONSTRAINT "user_relationship_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "user_relationship" ADD CONSTRAINT "user_relationship_address_id_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "address"("id");

/**
 * CUSTOM SQL STATEMENTS
 */

CREATE OR REPLACE FUNCTION set_updated_at_fn()
    RETURNS trigger
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$;
--> statement-breakpoint

--

CREATE OR REPLACE FUNCTION add_updated_at_triggers_fn()
    RETURNS void
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
DECLARE
    record RECORD;
BEGIN
    FOR record IN
        SELECT DISTINCT
            table_name
        FROM
            information_schema.columns
        WHERE
            table_schema = 'public' AND
            column_name = 'updated_at'
    LOOP
        EXECUTE format(
            'CREATE OR REPLACE TRIGGER "%s_bu_trig" BEFORE UPDATE ON "public"."%s" FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION "public".set_updated_at_fn();',
			record.table_name,
			record.table_name
        );
    END LOOP;
END;
$$;
--> statement-breakpoint

SELECT "public".add_updated_at_triggers_fn();--> statement-breakpoint
DROP FUNCTION "public".add_updated_at_triggers_fn();--> statement-breakpoint

--

CREATE OR REPLACE FUNCTION set_deferrable_fk_constraints_fn()
    RETURNS void
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
DECLARE
    record RECORD;
BEGIN
    FOR record IN
        SELECT
            conname,
            conrelid::regclass AS table_name
        FROM
            pg_constraint
        WHERE
            contype = 'f' AND
            connamespace = 'public'::regnamespace AND
            NOT condeferrable
    LOOP
        EXECUTE format(
            'ALTER TABLE %s ALTER CONSTRAINT %I DEFERRABLE INITIALLY IMMEDIATE',
            record.table_name,
            record.conname
        );
    END LOOP;
END;
$$;
--> statement-breakpoint

SELECT "public".set_deferrable_fk_constraints_fn();--> statement-breakpoint
DROP FUNCTION "public".set_deferrable_fk_constraints_fn();--> statement-breakpoint

--
-- Used for Supabase Keepalive Workflow
-- Harden the Data API by exposing only the `api` schema and turning off the pg_graphql extension
--

CREATE SCHEMA IF NOT EXISTS api;--> statement-breakpoint
--GRANT USAGE ON SCHEMA API TO anon, authenticated;

CREATE OR REPLACE FUNCTION "api".keepalive_version()
    RETURNS TEXT
    LANGUAGE "sql"
    SET search_path = ''
    SECURITY DEFINER
AS $$
    SELECT version();
$$;
--> statement-breakpoint
