CREATE TYPE "public"."gender" AS ENUM('MALE', 'FEMALE');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "fmpxm18jipcc_unique" UNIQUE("provider_id","account_id")
);
--> statement-breakpoint
CREATE TABLE "address" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"line_1" text NOT NULL,
	"line_2" text,
	"city_municipality" text NOT NULL,
	"province_state_region" text NOT NULL,
	"postal_code" text NOT NULL,
	"country_code" text NOT NULL,
	"latitude" numeric,
	"longitude" numeric,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "c2nhrro7q3w6_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "audit_trail" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_trail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid NOT NULL,
	"organization_id" text NOT NULL,
	"user_id" text NOT NULL,
	"component" text NOT NULL,
	"action" text NOT NULL,
	"description" text NOT NULL,
	"record_table" text,
	"record_id" text,
	"record_data_old" jsonb,
	"record_data_new" jsonb,
	"ip_address" text,
	"user_agent" text,
	"logged_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "oxbb5xf5czye_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "invitation" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"inviter_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "qticc263mdrn_unique" UNIQUE("organization_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "object_storage" (
	"id" text PRIMARY KEY NOT NULL,
	"size" bigint NOT NULL,
	"mime_type" text,
	"hash_sha256" text NOT NULL,
	"is_public" boolean DEFAULT false NOT NULL,
	"is_uploaded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ectz8nfqt8mj_unique" UNIQUE("hash_sha256")
);
--> statement-breakpoint
CREATE TABLE "object_storage_acl" (
	"object_storage_id" text NOT NULL,
	"user_id" text NOT NULL,
	"mode" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "i9c1la91qvh8_unique" UNIQUE("object_storage_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"logo" text,
	"metadata" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "vcr7tjb6whfs_unique" UNIQUE("slug"),
	CONSTRAINT "vcr7tjb6whfs_check" CHECK (slug = LOWER(slug))
);
--> statement-breakpoint
CREATE TABLE "permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component" text NOT NULL,
	"action" text NOT NULL,
	"role_id" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ctaxe84nuq66_unique" UNIQUE("component","action","role_id")
);
--> statement-breakpoint
CREATE TABLE "role" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "629pi1o76z2z_unique" UNIQUE("name"),
	CONSTRAINT "629pi1o76z2z_check" CHECK (name = LOWER(name))
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"active_organization_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "d3j63aa60m5j_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "upload" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"is_committed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upload_attachment" (
	"upload_id" text NOT NULL,
	"object_storage_id" text NOT NULL,
	CONSTRAINT "23aso68ioiyj_unique" UNIQUE("upload_id","object_storage_id")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"username" text NOT NULL,
	"display_username" text,
	"two_factor_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mfll9xelu6gc_unique" UNIQUE("email"),
	CONSTRAINT "2qajnnnraodw_unique" UNIQUE("username"),
	CONSTRAINT "mfll9xelu6gc_check" CHECK (email = LOWER(email)),
	CONSTRAINT "2qajnnnraodw_check" CHECK (username = LOWER(username))
);
--> statement-breakpoint
CREATE TABLE "user_attribute" (
	"user_id" text PRIMARY KEY NOT NULL,
	"is_locked" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_profile" (
	"user_id" text PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"middle_name" text,
	"last_name" text NOT NULL,
	"name_extension" text,
	"gender" "gender" NOT NULL,
	"backup_phone_number" text,
	"address_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_relationship" (
	"user_id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"relationship" text NOT NULL,
	"phone_number" text NOT NULL,
	"backup_phone_number" text,
	"email" text,
	"address_id" bigint,
	"is_emergency_contact" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "46hrccabod8t_unique" UNIQUE("identifier")
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "ame54f8rq90m_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "audit_trail" ADD CONSTRAINT "xhbjm31r4h6s_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "audit_trail" ADD CONSTRAINT "kg5nldbccqqf_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "vsccwld046ul_fkey" FOREIGN KEY ("inviter_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "dwh0vrawi8kc_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "to5af3ntvzc0_fkey" FOREIGN KEY ("role") REFERENCES "public"."role"("name") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "0xl3tx6iju2c_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "ey8flhlguwkb_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "kn8m1fkitar0_fkey" FOREIGN KEY ("role") REFERENCES "public"."role"("name") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "object_storage_acl" ADD CONSTRAINT "xabdmms1rce4_fkey" FOREIGN KEY ("object_storage_id") REFERENCES "public"."object_storage"("id") ON DELETE cascade ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "object_storage_acl" ADD CONSTRAINT "68ghia6fpgvj_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "permission" ADD CONSTRAINT "7vz0lkc6bbu7_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "11rzmcpm3uv0_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "n6ebx1rg81k4_fkey" FOREIGN KEY ("active_organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "upload" ADD CONSTRAINT "dwolixf6w8hp_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "upload_attachment" ADD CONSTRAINT "c0g7vcldgcc1_fkey" FOREIGN KEY ("upload_id") REFERENCES "public"."upload"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "upload_attachment" ADD CONSTRAINT "o7xm4my0uq10_fkey" FOREIGN KEY ("object_storage_id") REFERENCES "public"."object_storage"("id") ON DELETE cascade ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "user_attribute" ADD CONSTRAINT "nhsl7a2vq0j4_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "user_profile" ADD CONSTRAINT "eem2zxeduyfv_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "user_profile" ADD CONSTRAINT "qun382y3zidg_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "user_relationship" ADD CONSTRAINT "pa6kbv7tko20_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
ALTER TABLE "user_relationship" ADD CONSTRAINT "7ms4oot44t7x_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY IMMEDIATE;--> statement-breakpoint
CREATE INDEX "ame54f8rq90m_index" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "xhbjm31r4h6s_index" ON "audit_trail" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "kg5nldbccqqf_index" ON "audit_trail" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "vsccwld046ul_index" ON "invitation" USING btree ("inviter_id");--> statement-breakpoint
CREATE INDEX "dwh0vrawi8kc_index" ON "invitation" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "to5af3ntvzc0_index" ON "invitation" USING btree ("role");--> statement-breakpoint
CREATE INDEX "0xl3tx6iju2c_index" ON "member" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ey8flhlguwkb_index" ON "member" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "kn8m1fkitar0_index" ON "member" USING btree ("role");--> statement-breakpoint
CREATE INDEX "xabdmms1rce4_index" ON "object_storage_acl" USING btree ("object_storage_id");--> statement-breakpoint
CREATE INDEX "68ghia6fpgvj_index" ON "object_storage_acl" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "7vz0lkc6bbu7_index" ON "permission" USING btree ("role_id");--> statement-breakpoint
CREATE INDEX "11rzmcpm3uv0_index" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "n6ebx1rg81k4_index" ON "session" USING btree ("active_organization_id");--> statement-breakpoint
CREATE INDEX "dwolixf6w8hp_index" ON "upload" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "c0g7vcldgcc1_index" ON "upload_attachment" USING btree ("upload_id");--> statement-breakpoint
CREATE INDEX "o7xm4my0uq10_index" ON "upload_attachment" USING btree ("object_storage_id");--> statement-breakpoint
CREATE INDEX "nhsl7a2vq0j4_index" ON "user_attribute" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "eem2zxeduyfv_index" ON "user_profile" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "qun382y3zidg_index" ON "user_profile" USING btree ("address_id");--> statement-breakpoint
CREATE INDEX "pa6kbv7tko20_index" ON "user_relationship" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "7ms4oot44t7x_index" ON "user_relationship" USING btree ("address_id");

/**
 * CUSTOM SQL STATEMENTS
 */

CREATE OR REPLACE FUNCTION set_updated_at_fn()
    RETURNS trigger
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION add_updated_at_triggers_fn()
    RETURNS void
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
DECLARE
    record RECORD;
BEGIN
    FOR record IN
        SELECT DISTINCT
            table_name
        FROM
            information_schema.columns
        WHERE
            table_schema = 'public' AND
            column_name IN ('created_at', 'updated_at')
    LOOP
        EXECUTE format(
            'CREATE OR REPLACE TRIGGER "%s_bu_trig" BEFORE UPDATE ON "public"."%s" FOR EACH ROW EXECUTE FUNCTION "public".set_updated_at_fn();',
			record.table_name,
			record.table_name
        );
    END LOOP;
END;
$$;

SELECT "public".add_updated_at_triggers_fn();

DROP FUNCTION "public".add_updated_at_triggers_fn();
