CREATE SCHEMA "archive";
--> statement-breakpoint
CREATE TYPE "gender" AS ENUM('MALE', 'FEMALE');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_provider_id_account_id_unique" UNIQUE("provider_id","account_id")
);
--> statement-breakpoint
CREATE TABLE "address" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
	"line_1" text NOT NULL,
	"line_2" text,
	"city_municipality" text NOT NULL,
	"province_state_region" text NOT NULL,
	"postal_code" text NOT NULL,
	"country_code" text NOT NULL,
	"latitude" numeric,
	"longitude" numeric,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_trail" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_trail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
	"organization_id" text,
	"user_id" text,
	"component" text NOT NULL,
	"action" text NOT NULL,
	"description" text NOT NULL,
	"records" jsonb,
	"ip_address" text,
	"user_agent" text,
	"logged_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invitation" (
	"id" text PRIMARY KEY,
	"email" text NOT NULL,
	"inviter_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "key_counter" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "key_counter_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
	"key" text NOT NULL UNIQUE,
	"counter" bigint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "key_value" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "key_value_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
	"key" text NOT NULL UNIQUE,
	"value" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_organization_id_user_id_unique" UNIQUE("organization_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "object_storage" (
	"id" text PRIMARY KEY,
	"size" bigint NOT NULL,
	"mime_type" text,
	"hash_sha256" text NOT NULL UNIQUE,
	"is_public" boolean DEFAULT false NOT NULL,
	"is_uploaded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "object_storage_acl" (
	"object_storage_id" text NOT NULL,
	"user_id" text NOT NULL,
	"mode" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "object_storage_acl_object_storage_id_user_id_unique" UNIQUE("object_storage_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"slug" text NOT NULL UNIQUE,
	"logo" text,
	"metadata" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organization_slug_check" CHECK (slug = LOWER(slug))
);
--> statement-breakpoint
CREATE TABLE "permission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"component" text NOT NULL,
	"action" text NOT NULL,
	"role_id" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "permission_component_action_role_id_unique" UNIQUE("component","action","role_id")
);
--> statement-breakpoint
CREATE TABLE "role" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text NOT NULL UNIQUE,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "role_name_check" CHECK (name = LOWER(name))
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"token" text NOT NULL UNIQUE,
	"expires_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"active_organization_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "two_factor" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"secret" text,
	"backup_codes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upload" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"is_committed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upload_attachment" (
	"upload_id" text NOT NULL,
	"object_storage_id" text NOT NULL,
	CONSTRAINT "upload_attachment_upload_id_object_storage_id_unique" UNIQUE("upload_id","object_storage_id")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"username" text NOT NULL UNIQUE,
	"display_username" text,
	"two_factor_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_check" CHECK (email = LOWER(email)),
	CONSTRAINT "user_username_check" CHECK (username = LOWER(username))
);
--> statement-breakpoint
CREATE TABLE "user_attribute" (
	"user_id" text PRIMARY KEY,
	"is_locked" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_profile" (
	"user_id" text PRIMARY KEY,
	"first_name" text NOT NULL,
	"middle_name" text,
	"last_name" text NOT NULL,
	"name_extension" text,
	"gender" "gender" NOT NULL,
	"backup_phone_number" text,
	"address_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_relationship" (
	"user_id" text PRIMARY KEY,
	"name" text NOT NULL,
	"relationship" text NOT NULL,
	"phone_number" text NOT NULL,
	"backup_phone_number" text,
	"email" text,
	"address_id" bigint,
	"is_emergency_contact" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY,
	"identifier" text NOT NULL UNIQUE,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "account_user_id_index" ON "account" ("user_id");--> statement-breakpoint
CREATE INDEX "audit_trail_organization_id_index" ON "audit_trail" ("organization_id");--> statement-breakpoint
CREATE INDEX "audit_trail_user_id_index" ON "audit_trail" ("user_id");--> statement-breakpoint
CREATE INDEX "invitation_email_index" ON "invitation" ("email");--> statement-breakpoint
CREATE INDEX "invitation_inviter_id_index" ON "invitation" ("inviter_id");--> statement-breakpoint
CREATE INDEX "invitation_organization_id_index" ON "invitation" ("organization_id");--> statement-breakpoint
CREATE INDEX "member_user_id_index" ON "member" ("user_id");--> statement-breakpoint
CREATE INDEX "object_storage_acl_user_id_index" ON "object_storage_acl" ("user_id");--> statement-breakpoint
CREATE INDEX "permission_role_id_index" ON "permission" ("role_id");--> statement-breakpoint
CREATE INDEX "session_user_id_index" ON "session" ("user_id");--> statement-breakpoint
CREATE INDEX "session_active_organization_id_index" ON "session" ("active_organization_id");--> statement-breakpoint
CREATE INDEX "two_factor_user_id_index" ON "two_factor" ("user_id");--> statement-breakpoint
CREATE INDEX "upload_user_id_index" ON "upload" ("user_id");--> statement-breakpoint
CREATE INDEX "upload_attachment_object_storage_id_index" ON "upload_attachment" ("object_storage_id");--> statement-breakpoint
CREATE INDEX "user_profile_address_id_index" ON "user_profile" ("address_id");--> statement-breakpoint
CREATE INDEX "user_relationship_address_id_index" ON "user_relationship" ("address_id");--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "audit_trail" ADD CONSTRAINT "audit_trail_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "audit_trail" ADD CONSTRAINT "audit_trail_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_inviter_id_user_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "invitation" ADD CONSTRAINT "invitation_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_organization_id_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "object_storage_acl" ADD CONSTRAINT "object_storage_acl_object_storage_id_object_storage_id_fkey" FOREIGN KEY ("object_storage_id") REFERENCES "object_storage"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "object_storage_acl" ADD CONSTRAINT "object_storage_acl_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "permission" ADD CONSTRAINT "permission_role_id_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("id");--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_active_organization_id_organization_id_fkey" FOREIGN KEY ("active_organization_id") REFERENCES "organization"("id");--> statement-breakpoint
ALTER TABLE "two_factor" ADD CONSTRAINT "two_factor_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "upload" ADD CONSTRAINT "upload_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "upload_attachment" ADD CONSTRAINT "upload_attachment_upload_id_upload_id_fkey" FOREIGN KEY ("upload_id") REFERENCES "upload"("id");--> statement-breakpoint
ALTER TABLE "upload_attachment" ADD CONSTRAINT "upload_attachment_object_storage_id_object_storage_id_fkey" FOREIGN KEY ("object_storage_id") REFERENCES "object_storage"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "user_attribute" ADD CONSTRAINT "user_attribute_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "user_profile" ADD CONSTRAINT "user_profile_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "user_profile" ADD CONSTRAINT "user_profile_address_id_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "address"("id");--> statement-breakpoint
ALTER TABLE "user_relationship" ADD CONSTRAINT "user_relationship_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "user_relationship" ADD CONSTRAINT "user_relationship_address_id_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "address"("id");

/**
 * CUSTOM SQL STATEMENTS
 */

--
-- Add triggers to tables containing updated_at columns so
-- the timestamp is refreshed whenever a row is modified
--

CREATE OR REPLACE FUNCTION set_updated_at_fn()
    RETURNS trigger
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION add_updated_at_triggers_fn()
    RETURNS void
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
DECLARE
    record RECORD;
BEGIN
    FOR record IN
        SELECT DISTINCT
            table_name
        FROM
            information_schema.columns
        WHERE
            table_schema = 'public' AND
            column_name = 'updated_at'
    LOOP
        EXECUTE format(
            'CREATE OR REPLACE TRIGGER "%s_bu_trig" BEFORE UPDATE ON "public"."%s" FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION "public".set_updated_at_fn();',
			record.table_name,
			record.table_name
        );
    END LOOP;
END;
$$;
--> statement-breakpoint

SELECT "public".add_updated_at_triggers_fn();--> statement-breakpoint
DROP FUNCTION "public".add_updated_at_triggers_fn();--> statement-breakpoint

--
-- Make foreign key constraints deferrable
--

CREATE OR REPLACE FUNCTION set_deferrable_fk_constraints_fn()
    RETURNS void
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
DECLARE
    record RECORD;
BEGIN
    FOR record IN
        SELECT
            conname,
            conrelid::regclass AS table_name
        FROM
            pg_constraint
        WHERE
            contype = 'f' AND
            connamespace = 'public'::regnamespace AND
            NOT condeferrable
    LOOP
        EXECUTE format(
            'ALTER TABLE %s ALTER CONSTRAINT %I DEFERRABLE INITIALLY IMMEDIATE',
            record.table_name,
            record.conname
        );
    END LOOP;
END;
$$;
--> statement-breakpoint

SELECT "public".set_deferrable_fk_constraints_fn();--> statement-breakpoint
DROP FUNCTION "public".set_deferrable_fk_constraints_fn();--> statement-breakpoint

--
-- Used for Supabase Keepalive Workflow
-- Harden the Data API by exposing only the `api` schema and turning off the pg_graphql extension
--

CREATE SCHEMA IF NOT EXISTS api;--> statement-breakpoint
--GRANT USAGE ON SCHEMA API TO anon, authenticated;

CREATE OR REPLACE FUNCTION "api".keepalive_version()
    RETURNS TEXT
    LANGUAGE "sql"
    SET search_path = ''
    SECURITY DEFINER
AS $$
    SELECT version();
$$;
--> statement-breakpoint

--
-- Create an archive schema to retain selected rows deleted from the public schema
-- Will only add the triggers if both tables exist in the `public` and `archive` schema
--

CREATE OR REPLACE FUNCTION archive_deleted_row_fn()
    RETURNS trigger
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
BEGIN
    EXECUTE format(
        'INSERT INTO %I.%I SELECT * FROM jsonb_populate_record(NULL::%I.%I, to_jsonb($1))',
        'archive',
        TG_TABLE_NAME,
        'archive',
        TG_TABLE_NAME
    ) USING OLD;

    RETURN OLD;
END;
$$;--> statement-breakpoint

CREATE OR REPLACE FUNCTION add_archive_delete_triggers_fn()
    RETURNS void
    LANGUAGE "plpgsql"
    SET search_path = ''
AS $$
DECLARE
    record RECORD;
BEGIN
    FOR record IN
        SELECT
            source.table_name
        FROM
            information_schema.tables source
        INNER JOIN information_schema.tables archive
            ON archive.table_schema = 'archive'
            AND archive.table_name = source.table_name
            AND archive.table_type = 'BASE TABLE'
        WHERE
            source.table_schema = 'public'
            AND source.table_type = 'BASE TABLE'
    LOOP
        EXECUTE format(
            'CREATE OR REPLACE TRIGGER %I AFTER DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION %I.archive_deleted_row_fn();',
            record.table_name || '_ad_trig',
            'public',
            record.table_name,
            'public'
        );
    END LOOP;
END;
$$;--> statement-breakpoint

SELECT "public".add_archive_delete_triggers_fn();--> statement-breakpoint
DROP FUNCTION "public".add_archive_delete_triggers_fn();--> statement-breakpoint

--> statement-breakpoint
-- Product table (domain)
CREATE TABLE "product" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() UNIQUE NOT NULL,
	"organization_id" text NOT NULL,
	"name" text NOT NULL,
	"ingredients" text,
	"price" numeric NOT NULL,
	"is_available" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "product" ADD CONSTRAINT "product_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX ON "product" ("organization_id");--> statement-breakpoint
CREATE TRIGGER set_product_updated_at
BEFORE UPDATE ON "product"
FOR EACH ROW EXECUTE FUNCTION set_updated_at_fn();
--> statement-breakpoint

-- Order table (domain)
CREATE TYPE "order_status" AS ENUM('pending','cooking','looking_for_rider','ready_to_pick_up','rider_is_on_the_way','completed','cancelled');--> statement-breakpoint
CREATE TYPE "delivery_type" AS ENUM('self_pickup','lalamove','other_courier');--> statement-breakpoint
CREATE TABLE "order" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() UNIQUE NOT NULL,
	"organization_id" text NOT NULL,
	"customer_name" text NOT NULL,
	"contact_number" text NOT NULL,
	"contact_number_2" text,
	"delivery_type" "delivery_type" NOT NULL,
	"amount_to_pay" numeric NOT NULL,
	"proof_of_payment_object_storage_id" text,
	"status" "order_status" DEFAULT 'pending' NOT NULL,
	"notes" text,
	"delivery_address" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_proof_of_payment_object_storage_id_fk" FOREIGN KEY ("proof_of_payment_object_storage_id") REFERENCES "public"."object_storage"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX ON "order" ("organization_id");--> statement-breakpoint
CREATE INDEX ON "order" ("status");--> statement-breakpoint
CREATE INDEX ON "order" ("created_at");--> statement-breakpoint
CREATE TRIGGER set_order_updated_at
BEFORE UPDATE ON "order"
FOR EACH ROW EXECUTE FUNCTION set_updated_at_fn();
--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "downpayment" numeric;
--> statement-breakpoint

-- Order item table (domain)
CREATE TABLE "order_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"order_id" bigint NOT NULL,
	"product_id" bigint,
	"name" text NOT NULL,
	"size_name" text,
	"quantity" integer DEFAULT 1 NOT NULL,
	"price" numeric NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_order_id_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX ON "order_item" ("order_id");--> statement-breakpoint
CREATE INDEX ON "order_item" ("product_id");--> statement-breakpoint
CREATE TRIGGER set_order_item_updated_at
BEFORE UPDATE ON "order_item"
FOR EACH ROW EXECUTE FUNCTION set_updated_at_fn();

--> statement-breakpoint
-- Product category enum and extensions
CREATE TYPE "product_category" AS ENUM('bilao_package', 'bundle_package', 'single_order');--> statement-breakpoint
CREATE TYPE "product_tag" AS ENUM('new', 'best_seller', 'seasonal', 'limited');--> statement-breakpoint
ALTER TABLE "product" ADD COLUMN "category" product_category NOT NULL DEFAULT 'single_order';--> statement-breakpoint
ALTER TABLE "product" ADD COLUMN "tags" product_tag[] NOT NULL DEFAULT '{}';--> statement-breakpoint
CREATE TABLE "product_size" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_size_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"product_id" bigint NOT NULL,
	"name" text NOT NULL,
	"price" numeric NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "product_size" ADD CONSTRAINT "product_size_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX ON "product_size" ("product_id");--> statement-breakpoint
CREATE TRIGGER set_product_size_updated_at
BEFORE UPDATE ON "product_size"
FOR EACH ROW EXECUTE FUNCTION set_updated_at_fn();

--> statement-breakpoint
-- Product image support
ALTER TABLE "product" ADD COLUMN "image_object_storage_id" text;--> statement-breakpoint
ALTER TABLE "product" ADD CONSTRAINT "product_image_object_storage_id_fk" FOREIGN KEY ("image_object_storage_id") REFERENCES "public"."object_storage"("id") ON DELETE set null ON UPDATE no action;

--> statement-breakpoint
-- Order delivery date and 10-char tracking code
ALTER TABLE "order" ADD COLUMN "delivery_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "tracking_code" text NOT NULL DEFAULT '';--> statement-breakpoint
CREATE UNIQUE INDEX "order_tracking_code_unique" ON "order" ("tracking_code");--> statement-breakpoint
CREATE INDEX "order_delivery_at_index" ON "order" ("delivery_at");--> statement-breakpoint
ALTER TABLE "order" ALTER COLUMN "tracking_code" DROP DEFAULT;--> statement-breakpoint
-- Remaining balance payment method and proof
ALTER TABLE "order" ADD COLUMN "remaining_balance_payment_method" text;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "remaining_balance_proof_object_storage_id" text;--> statement-breakpoint
ALTER TABLE "order" ADD CONSTRAINT "order_remaining_balance_proof_fk" FOREIGN KEY ("remaining_balance_proof_object_storage_id") REFERENCES "object_storage"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

--> statement-breakpoint
-- Proof of payment status tracking
ALTER TABLE "order" ADD COLUMN "proof_of_payment_status" text;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "remaining_balance_proof_status" text;--> statement-breakpoint
-- Remaining balance GCash sender info
ALTER TABLE "order" ADD COLUMN "remaining_balance_sender_name" text;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "remaining_balance_sender_number" text;--> statement-breakpoint
ALTER TABLE "order" ADD COLUMN "remaining_balance_amount_sent" numeric;
