import { drizzle } from 'drizzle-orm/postgres-js'
import postgresJs from 'postgres'

export type TDbClientConfig = {
    host: string
    port: number
    database: string
    user: string
    pass: string
}

const postgresClientOptions = {
    max: 1,
    idle_timeout: 0,
    /**
     * Hide notices generated by the client
     * https://github.com/porsager/postgres/issues/646#issuecomment-1642584789
     */
    onnotice: () => {
        /* EMPTY */
    },
}

export const dbClient = (passedConfig: string | TDbClientConfig) =>
    drizzle({
        client:
            typeof passedConfig === 'string'
                ? postgresJs(passedConfig, postgresClientOptions)
                : postgresJs({
                      ...passedConfig,
                      ...postgresClientOptions,
                  }),
    })

export default dbClient
