import { drizzle } from 'drizzle-orm/postgres-js'
import postgresJs from 'postgres'

export const dbClient = (passedConfig: {
    host: string
    port: number
    database: string
    user: string
    pass: string
}) =>
    drizzle({
        client: postgresJs({
            ...passedConfig,
            max: 1,
            prepare: false,
            idle_timeout: 0,
            // Hide notices generated by the client
            // https://github.com/porsager/postgres/issues/646#issuecomment-1642584789
            onnotice: () => {
                /* EMPTY */
            },
        }),
    })

export default dbClient
