import { drizzle } from 'drizzle-orm/postgres-js'
import postgresJs from 'postgres'

import * as schema from './schema.js'

export const dbClient = (env: THonoBindings) =>
    drizzle({
        client: postgresJs({
            host: env.HYPERION_HD.host,
            port: Number(env.HYPERION_HD.port),
            database: env.HYPERION_HD.database,
            user: env.HYPERION_HD.user,
            pass: env.HYPERION_HD.password,
            // Hide notices generated by the client
            // https://github.com/porsager/postgres/issues/646#issuecomment-1642584789
            onnotice: () => {
                /* EMPTY */
            },
        }),
        schema,
        // https://orm.drizzle.team/docs/sql-schema-declaration#camel-and-snake-casing
        casing: 'snake_case',
    })

export default dbClient
