#!/usr/bin/env bash

echo
echo ==============================
echo = BEGIN: git post-merge hook =
echo ==============================
echo

# Check if certain files were modified by the merge process
validatorChanged=$( git diff --name-only 'HEAD@{1}' HEAD | ( grep 'packages/validator/src/' || true ) )
backendChanged=$( git diff --name-only 'HEAD@{1}' HEAD | ( grep 'packages/backend/src/' || true ) )

# Re-install dependencies
echo Installing project dependencies...
pnpm -r i
echo

# Build validator package
if [[ $validatorChanged != '' ]]; then
    echo Building validator package...
    pnpm --filter="@hyperion/validator" exec rm -rf dist
    pnpm --filter="@hyperion/validator" exec rm -rf *.tsbuildinfo
    pnpm --filter="@hyperion/validator" build
    echo
fi

# Build backend package
if [[ $backendChanged != '' ]]; then
    echo Building backend package...
    pnpm --filter="@hyperion/backend" exec rm -rf dist
    pnpm --filter="@hyperion/backend" exec rm -rf *.tsbuildinfo
    pnpm --filter="@hyperion/backend" build
    echo
fi

echo
echo ============================
echo = END: git post-merge hook =
echo ============================
echo

exit 0
