#!/usr/bin/env bash

echo
echo ==============================
echo = BEGIN: git post-merge hook =
echo ==============================
echo

# Check if certain files were modified by the merge process
lockFileChanged=$( git diff --name-only 'HEAD@{1}' HEAD | ( grep 'pnpm-lock.yaml' || true ) )
validatorChanged=$( git diff --name-only 'HEAD@{1}' HEAD | ( grep 'packages/validator/src/' || true ) )

# Re-install dependencies when there are modifications to pnpm lockfile
if [[ $lockFileChanged != '' ]]; then
    echo Installing project dependencies...
    pnpm i
    echo
fi

# Build validator package
if [[ $validatorChanged != '' ]]; then
    echo Building validator package...
    pnpm --filter="@hyperion/validator" exec rm -rf dist
    pnpm --filter="@hyperion/validator" build
    echo
fi

echo
echo ============================
echo = END: git post-merge hook =
echo ============================
echo

exit 0
